# Generated by Django 5.0.1 on 2024-01-25 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
